# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/levi/Documents/home/projects/RenderEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/levi/Documents/home/projects/RenderEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/levi/Documents/home/projects/RenderEngine/CMakeFiles /home/levi/Documents/home/projects/RenderEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/levi/Documents/home/projects/RenderEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named RenderEngine

# Build rule for target.
RenderEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RenderEngine
.PHONY : RenderEngine

# fast build rule for target.
RenderEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/build
.PHONY : RenderEngine/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/main.cpp.s
.PHONY : main.cpp.s

src/physics/physicsEngine.o: src/physics/physicsEngine.cpp.o
.PHONY : src/physics/physicsEngine.o

# target to build an object file
src/physics/physicsEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/physics/physicsEngine.cpp.o
.PHONY : src/physics/physicsEngine.cpp.o

src/physics/physicsEngine.i: src/physics/physicsEngine.cpp.i
.PHONY : src/physics/physicsEngine.i

# target to preprocess a source file
src/physics/physicsEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/physics/physicsEngine.cpp.i
.PHONY : src/physics/physicsEngine.cpp.i

src/physics/physicsEngine.s: src/physics/physicsEngine.cpp.s
.PHONY : src/physics/physicsEngine.s

# target to generate assembly for a file
src/physics/physicsEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/physics/physicsEngine.cpp.s
.PHONY : src/physics/physicsEngine.cpp.s

src/physics/physicsObject.o: src/physics/physicsObject.cpp.o
.PHONY : src/physics/physicsObject.o

# target to build an object file
src/physics/physicsObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/physics/physicsObject.cpp.o
.PHONY : src/physics/physicsObject.cpp.o

src/physics/physicsObject.i: src/physics/physicsObject.cpp.i
.PHONY : src/physics/physicsObject.i

# target to preprocess a source file
src/physics/physicsObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/physics/physicsObject.cpp.i
.PHONY : src/physics/physicsObject.cpp.i

src/physics/physicsObject.s: src/physics/physicsObject.cpp.s
.PHONY : src/physics/physicsObject.s

# target to generate assembly for a file
src/physics/physicsObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/physics/physicsObject.cpp.s
.PHONY : src/physics/physicsObject.cpp.s

src/primitives/cube.o: src/primitives/cube.cpp.o
.PHONY : src/primitives/cube.o

# target to build an object file
src/primitives/cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/cube.cpp.o
.PHONY : src/primitives/cube.cpp.o

src/primitives/cube.i: src/primitives/cube.cpp.i
.PHONY : src/primitives/cube.i

# target to preprocess a source file
src/primitives/cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/cube.cpp.i
.PHONY : src/primitives/cube.cpp.i

src/primitives/cube.s: src/primitives/cube.cpp.s
.PHONY : src/primitives/cube.s

# target to generate assembly for a file
src/primitives/cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/cube.cpp.s
.PHONY : src/primitives/cube.cpp.s

src/primitives/plane.o: src/primitives/plane.cpp.o
.PHONY : src/primitives/plane.o

# target to build an object file
src/primitives/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/plane.cpp.o
.PHONY : src/primitives/plane.cpp.o

src/primitives/plane.i: src/primitives/plane.cpp.i
.PHONY : src/primitives/plane.i

# target to preprocess a source file
src/primitives/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/plane.cpp.i
.PHONY : src/primitives/plane.cpp.i

src/primitives/plane.s: src/primitives/plane.cpp.s
.PHONY : src/primitives/plane.s

# target to generate assembly for a file
src/primitives/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/plane.cpp.s
.PHONY : src/primitives/plane.cpp.s

src/primitives/sphere.o: src/primitives/sphere.cpp.o
.PHONY : src/primitives/sphere.o

# target to build an object file
src/primitives/sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/sphere.cpp.o
.PHONY : src/primitives/sphere.cpp.o

src/primitives/sphere.i: src/primitives/sphere.cpp.i
.PHONY : src/primitives/sphere.i

# target to preprocess a source file
src/primitives/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/sphere.cpp.i
.PHONY : src/primitives/sphere.cpp.i

src/primitives/sphere.s: src/primitives/sphere.cpp.s
.PHONY : src/primitives/sphere.s

# target to generate assembly for a file
src/primitives/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/primitives/sphere.cpp.s
.PHONY : src/primitives/sphere.cpp.s

src/render/camera.o: src/render/camera.cpp.o
.PHONY : src/render/camera.o

# target to build an object file
src/render/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/camera.cpp.o
.PHONY : src/render/camera.cpp.o

src/render/camera.i: src/render/camera.cpp.i
.PHONY : src/render/camera.i

# target to preprocess a source file
src/render/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/camera.cpp.i
.PHONY : src/render/camera.cpp.i

src/render/camera.s: src/render/camera.cpp.s
.PHONY : src/render/camera.s

# target to generate assembly for a file
src/render/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/camera.cpp.s
.PHONY : src/render/camera.cpp.s

src/render/gpu_interface/EBO.o: src/render/gpu_interface/EBO.cpp.o
.PHONY : src/render/gpu_interface/EBO.o

# target to build an object file
src/render/gpu_interface/EBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/EBO.cpp.o
.PHONY : src/render/gpu_interface/EBO.cpp.o

src/render/gpu_interface/EBO.i: src/render/gpu_interface/EBO.cpp.i
.PHONY : src/render/gpu_interface/EBO.i

# target to preprocess a source file
src/render/gpu_interface/EBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/EBO.cpp.i
.PHONY : src/render/gpu_interface/EBO.cpp.i

src/render/gpu_interface/EBO.s: src/render/gpu_interface/EBO.cpp.s
.PHONY : src/render/gpu_interface/EBO.s

# target to generate assembly for a file
src/render/gpu_interface/EBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/EBO.cpp.s
.PHONY : src/render/gpu_interface/EBO.cpp.s

src/render/gpu_interface/VAO.o: src/render/gpu_interface/VAO.cpp.o
.PHONY : src/render/gpu_interface/VAO.o

# target to build an object file
src/render/gpu_interface/VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/VAO.cpp.o
.PHONY : src/render/gpu_interface/VAO.cpp.o

src/render/gpu_interface/VAO.i: src/render/gpu_interface/VAO.cpp.i
.PHONY : src/render/gpu_interface/VAO.i

# target to preprocess a source file
src/render/gpu_interface/VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/VAO.cpp.i
.PHONY : src/render/gpu_interface/VAO.cpp.i

src/render/gpu_interface/VAO.s: src/render/gpu_interface/VAO.cpp.s
.PHONY : src/render/gpu_interface/VAO.s

# target to generate assembly for a file
src/render/gpu_interface/VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/VAO.cpp.s
.PHONY : src/render/gpu_interface/VAO.cpp.s

src/render/gpu_interface/VBO.o: src/render/gpu_interface/VBO.cpp.o
.PHONY : src/render/gpu_interface/VBO.o

# target to build an object file
src/render/gpu_interface/VBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/VBO.cpp.o
.PHONY : src/render/gpu_interface/VBO.cpp.o

src/render/gpu_interface/VBO.i: src/render/gpu_interface/VBO.cpp.i
.PHONY : src/render/gpu_interface/VBO.i

# target to preprocess a source file
src/render/gpu_interface/VBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/VBO.cpp.i
.PHONY : src/render/gpu_interface/VBO.cpp.i

src/render/gpu_interface/VBO.s: src/render/gpu_interface/VBO.cpp.s
.PHONY : src/render/gpu_interface/VBO.s

# target to generate assembly for a file
src/render/gpu_interface/VBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/VBO.cpp.s
.PHONY : src/render/gpu_interface/VBO.cpp.s

src/render/gpu_interface/shaderClass.o: src/render/gpu_interface/shaderClass.cpp.o
.PHONY : src/render/gpu_interface/shaderClass.o

# target to build an object file
src/render/gpu_interface/shaderClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/shaderClass.cpp.o
.PHONY : src/render/gpu_interface/shaderClass.cpp.o

src/render/gpu_interface/shaderClass.i: src/render/gpu_interface/shaderClass.cpp.i
.PHONY : src/render/gpu_interface/shaderClass.i

# target to preprocess a source file
src/render/gpu_interface/shaderClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/shaderClass.cpp.i
.PHONY : src/render/gpu_interface/shaderClass.cpp.i

src/render/gpu_interface/shaderClass.s: src/render/gpu_interface/shaderClass.cpp.s
.PHONY : src/render/gpu_interface/shaderClass.s

# target to generate assembly for a file
src/render/gpu_interface/shaderClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/shaderClass.cpp.s
.PHONY : src/render/gpu_interface/shaderClass.cpp.s

src/render/gpu_interface/texture.o: src/render/gpu_interface/texture.cpp.o
.PHONY : src/render/gpu_interface/texture.o

# target to build an object file
src/render/gpu_interface/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/texture.cpp.o
.PHONY : src/render/gpu_interface/texture.cpp.o

src/render/gpu_interface/texture.i: src/render/gpu_interface/texture.cpp.i
.PHONY : src/render/gpu_interface/texture.i

# target to preprocess a source file
src/render/gpu_interface/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/texture.cpp.i
.PHONY : src/render/gpu_interface/texture.cpp.i

src/render/gpu_interface/texture.s: src/render/gpu_interface/texture.cpp.s
.PHONY : src/render/gpu_interface/texture.s

# target to generate assembly for a file
src/render/gpu_interface/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/gpu_interface/texture.cpp.s
.PHONY : src/render/gpu_interface/texture.cpp.s

src/render/light.o: src/render/light.cpp.o
.PHONY : src/render/light.o

# target to build an object file
src/render/light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/light.cpp.o
.PHONY : src/render/light.cpp.o

src/render/light.i: src/render/light.cpp.i
.PHONY : src/render/light.i

# target to preprocess a source file
src/render/light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/light.cpp.i
.PHONY : src/render/light.cpp.i

src/render/light.s: src/render/light.cpp.s
.PHONY : src/render/light.s

# target to generate assembly for a file
src/render/light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/light.cpp.s
.PHONY : src/render/light.cpp.s

src/render/renderObject.o: src/render/renderObject.cpp.o
.PHONY : src/render/renderObject.o

# target to build an object file
src/render/renderObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/renderObject.cpp.o
.PHONY : src/render/renderObject.cpp.o

src/render/renderObject.i: src/render/renderObject.cpp.i
.PHONY : src/render/renderObject.i

# target to preprocess a source file
src/render/renderObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/renderObject.cpp.i
.PHONY : src/render/renderObject.cpp.i

src/render/renderObject.s: src/render/renderObject.cpp.s
.PHONY : src/render/renderObject.s

# target to generate assembly for a file
src/render/renderObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/renderObject.cpp.s
.PHONY : src/render/renderObject.cpp.s

src/render/renderer.o: src/render/renderer.cpp.o
.PHONY : src/render/renderer.o

# target to build an object file
src/render/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/renderer.cpp.o
.PHONY : src/render/renderer.cpp.o

src/render/renderer.i: src/render/renderer.cpp.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/renderer.cpp.i
.PHONY : src/render/renderer.cpp.i

src/render/renderer.s: src/render/renderer.cpp.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/render/renderer.cpp.s
.PHONY : src/render/renderer.cpp.s

vendor/src/stb_image.o: vendor/src/stb_image.cpp.o
.PHONY : vendor/src/stb_image.o

# target to build an object file
vendor/src/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/vendor/src/stb_image.cpp.o
.PHONY : vendor/src/stb_image.cpp.o

vendor/src/stb_image.i: vendor/src/stb_image.cpp.i
.PHONY : vendor/src/stb_image.i

# target to preprocess a source file
vendor/src/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/vendor/src/stb_image.cpp.i
.PHONY : vendor/src/stb_image.cpp.i

vendor/src/stb_image.s: vendor/src/stb_image.cpp.s
.PHONY : vendor/src/stb_image.s

# target to generate assembly for a file
vendor/src/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/vendor/src/stb_image.cpp.s
.PHONY : vendor/src/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RenderEngine"
	@echo "... stb_image"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/physics/physicsEngine.o"
	@echo "... src/physics/physicsEngine.i"
	@echo "... src/physics/physicsEngine.s"
	@echo "... src/physics/physicsObject.o"
	@echo "... src/physics/physicsObject.i"
	@echo "... src/physics/physicsObject.s"
	@echo "... src/primitives/cube.o"
	@echo "... src/primitives/cube.i"
	@echo "... src/primitives/cube.s"
	@echo "... src/primitives/plane.o"
	@echo "... src/primitives/plane.i"
	@echo "... src/primitives/plane.s"
	@echo "... src/primitives/sphere.o"
	@echo "... src/primitives/sphere.i"
	@echo "... src/primitives/sphere.s"
	@echo "... src/render/camera.o"
	@echo "... src/render/camera.i"
	@echo "... src/render/camera.s"
	@echo "... src/render/gpu_interface/EBO.o"
	@echo "... src/render/gpu_interface/EBO.i"
	@echo "... src/render/gpu_interface/EBO.s"
	@echo "... src/render/gpu_interface/VAO.o"
	@echo "... src/render/gpu_interface/VAO.i"
	@echo "... src/render/gpu_interface/VAO.s"
	@echo "... src/render/gpu_interface/VBO.o"
	@echo "... src/render/gpu_interface/VBO.i"
	@echo "... src/render/gpu_interface/VBO.s"
	@echo "... src/render/gpu_interface/shaderClass.o"
	@echo "... src/render/gpu_interface/shaderClass.i"
	@echo "... src/render/gpu_interface/shaderClass.s"
	@echo "... src/render/gpu_interface/texture.o"
	@echo "... src/render/gpu_interface/texture.i"
	@echo "... src/render/gpu_interface/texture.s"
	@echo "... src/render/light.o"
	@echo "... src/render/light.i"
	@echo "... src/render/light.s"
	@echo "... src/render/renderObject.o"
	@echo "... src/render/renderObject.i"
	@echo "... src/render/renderObject.s"
	@echo "... src/render/renderer.o"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... vendor/src/stb_image.o"
	@echo "... vendor/src/stb_image.i"
	@echo "... vendor/src/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

