name: RenderEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libglew-dev libglm-dev freeglut3-dev gcc-10 g++-10
    
    - name: Set up GCC 10
      run: |
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV
    
    - name: Verify C++20 support
      run: |
        echo '#include <iostream>
        #include <span>
        int main() {
          std::span<int> s;
          std::cout << "C++20 support confirmed\n";
          return 0;
        }' > test.cpp
        ${{ env.CXX }} -std=c++20 test.cpp -o test
        ./test
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
      env:
        CC: ${{ env.CC }}
        CXX: ${{ env.CXX }}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    
    - name: Run tests
      run: ctest -C ${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/build