name: RenderEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libglew-dev libglm-dev freeglut3-dev
    
    - name: Install GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10

    - name: Configure CMake
      run: |
        export CC=gcc-10
        export CXX=g++-10
        cmake -B ${{github.workspace}}/build
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    
    - name: Run tests
      run: ctest -C ${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/build
