name: RenderEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libglew-dev libglm-dev freeglut3-dev gcc g++
    
    - name: Set up GCC
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
      env:
        CC: ${{ env.CC }}
        CXX: ${{ env.CXX }}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    
    - name: Run tests
      run: ctest -C ${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/build